### ISSUE TITLE
Des petits trucs à revoir

### ISSUE THREAD

**Issue by benjGam** [Simplon-hdf/cheats-sheets-git-flow#25]
- [x] La présentation de Git manque de contenu
- [x] Manque d'une colonne `Exemple` dans le tableau des cheat sheet Git.
  - [x] Certaines explications de commandes ne sont pas claires
- [x] Le titre de [cette page](https://github.com/Simplon-hdf/cheats-sheets-git-flow/blob/develop/git/01-about-git/about-git.md) n'est pas cohèrent avec le nom du lien dans le README (En plus il est en Anglais alors que tout le reste est en Français)
- [x] La section `Index` dans le README n'a pas le bon titre
- [x] #32
- [x] Dans [cette page](https://github.com/Simplon-hdf/cheats-sheets-git-flow/blob/develop/git-flow/README.md) on ne parle pas de la méthodologie de travail `GitFlow`, seulement de l'outil.
  - [x] Manque d'une colonne `Exemple` dans le tableau de cheat sheet
  - [x] Certaines explications de commande ne sont pas claires
- [x] Il y a quelques erreurs syntaxiques (Certaines phrases ne commencent pas par des majuscules)

**Comment by benjGam** [comment]
[Commentaire](https://github.com/Simplon-hdf/cheats-sheets-git-flow/commit/b574c241fe1091555ebbaaa0eda0681bead261b1#r140372797)
[Commentaire](https://github.com/Simplon-hdf/cheats-sheets-git-flow/commit/121718660c106e643844ebbbff847b6df8fcc79f#r140372953)

**Comment by benjGam** [comment]
Il n'y a pas d'exemple pour la commande `git reset --hard`

**Comment by Hugo-walando** [comment]
fixed
